services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: tcp://docker:2376/

stages:
  - build
  - test
  - push

build:
  stage: build
  image: docker:19.03.1
  script:
    - docker build -t ineentho/git-semver-store .
    - docker save ineentho/git-semver-store > git-semver-store.tar
  artifacts:
    paths:
      - git-semver-store.tar
    expire_in: 1 week

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine:v0.7.0
  script: shellcheck *.sh

test:
  stage: test
  image: docker:19.03.1

  script:
    - docker load -i git-semver-store.tar
    - ./test.sh || exit 1

push:
  stage: push
  image: docker:19.03.1
  script:
    - docker load -i git-semver-store.tar
    - version=$(docker run --rm -e SSH_PRIVATE_KEY="$VERSIONS_INEENTHO_SSH_PRIVATE_KEY" ineentho/git-semver-store increment ssh://git@gitlab.henrik.ninja:10022/ineentho/versions-test.git test.txt patch "$CI_COMMIT_SHA")
    - image="ineentho/git-semver-store:$version"
    - docker tag ineentho/git-semver-store $image
    - docker push $image
