variables:
  DOCKER_HOST: tcp://docker:2376/

stages:
  - build
  - test
  - push

build:
  stage: build
  image: docker:19.03.5@sha256:0b90b0aefd15794e4d5bea2debc3b761c1d3481a92ec7166f8453652d0deba95
  services:
    - docker:19.03.5-dind@sha256:eee82e8076e846f428b4fc202a1d35352097cb12644c54b111c6155bc03f9edc
  tags:
    - dind
  script:
    - docker build -t ineentho/git-semver-store .
    - docker save ineentho/git-semver-store > git-semver-store.tar
  artifacts:
    paths:
      - git-semver-store.tar
    expire_in: 1 week

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine:v0.7.0@sha256:169a51b086af0ab181e32801c15deb78944bb433d4f2c0a21cc30d4e60547065
  script: shellcheck *.sh

test:
  stage: test
  image: docker:19.03.5@sha256:0b90b0aefd15794e4d5bea2debc3b761c1d3481a92ec7166f8453652d0deba95
  services:
    - docker:19.03.5-dind@sha256:eee82e8076e846f428b4fc202a1d35352097cb12644c54b111c6155bc03f9edc
  tags:
    - dind

  script:
    - docker load -i git-semver-store.tar
    - ./test.sh || exit 1

push:
  stage: push
  image: docker:19.03.5@sha256:0b90b0aefd15794e4d5bea2debc3b761c1d3481a92ec7166f8453652d0deba95
  services:
    - docker:19.03.5-dind@sha256:eee82e8076e846f428b4fc202a1d35352097cb12644c54b111c6155bc03f9edc
  tags:
    - dind
  only:
    refs:
      - master
  before_script:
    - docker login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD"
  script:
    - docker load -i git-semver-store.tar
    - version=$(docker run --rm -e SSH_PRIVATE_KEY="$VERSIONS_INEENTHO_SSH_PRIVATE_KEY" ineentho/git-semver-store increment ssh://git@gitlab.henrik.ninja:10022/ineentho/versions.git git-semver-store.txt patch "$CI_COMMIT_SHA")

    - image_version="ineentho/git-semver-store:$version"
    - docker tag ineentho/git-semver-store $image_version
    - docker push $image_version

    - image_latest="ineentho/git-semver-store:latest"
    - docker tag ineentho/git-semver-store $image_latest
    - docker push $image_latest
