services:
  - docker:19.03.1-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - push

before_script:
  - docker info

build:
  stage: build
  image: docker:19.03.1
  script:
    - docker build -t ineentho/git-semver-store .
    - docker save ineentho/git-semver-store > git-semver-store.tar
  artifacts:
    paths:
      - git-semver-store.tar
    expire_in: 1 week

test:
  stage: test
  image: docker:19.03.1

  script:
    - docker load -i git-semver-store.tar
    - docker run --rm ineentho/git-semver-store ssh://git@gitlab.henrik.ninja:10022/ineentho/versions-test.git test.txt patch $CI_COMMIT_SHA

push:
  stage: push
  image: docker:19.03.1
  script:
    - docker load -i git-semver-store.tar
    - docker push ineentho/git-semver-store
